<a href="https://colab.research.google.com/github/Johang74/Generador/blob/master/Reto_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Codigo

In [45]:
# Reto semana 6
# Johan David Gomez Gil

import numpy as np

rng = np.random.default_rng(123)
matriz_ventas = rng.integers(low = 0, high = 50, size = 30*10).reshape((30,10)) * 10000

def ventas_totales(matriz_ventas):
  ventas = []

  for i in range(10):
    total = 0
    for j in range(30):
      #print (matriz_ventas[j][i])
      total = total + matriz_ventas[j][i]
    ventas.append(total)
  #print(ventas)

  vendedor = 1
  for i in ventas:
    print (f"Vendedor {vendedor} ",i)
    vendedor +=1
  return ventas

def promedio_vendedores(matriz,vendedores):
  a = 0
  promedios = []
  for j in vendedores:
    a = 0
    prom = 0
    for i in range(30):
      a = a + matriz[i][j]

    prom = a / 30
    promedios.append(prom)

  j = 0
  for i in vendedores:
    print ("Promedio vendedor",i,":",promedios[j])
    j += 1

  return promedios




def calcular_comisiones(matriz):
  for i in range(30):
    for j in range(10):
      a = matriz[i][j]
      if  matriz[i][j] >= 200000 and matriz[i][j] <= 800000:
        matriz[i][j] = matriz[i][j] * 0.05
        tipo_bonificacion = "A"
      elif matriz[i][j] > 800000 and matriz[i][j] <= 1500000:
        matriz[i][j] = matriz[i][j] * 0.1
        tipo_bonificacion = "B"
      elif matriz[i][j] > 1500000:
        tipo_bonificacion = "C"
        matriz[i][j] = matriz[i][j] * 0.15
  print("COMISIONES-----------------------------------------------------------")
  print (matriz)
  return matriz

def calcular_promedios(matriz, vendedores, semana_quincena): # Semana_quincena = [1,1], el primer valor si es UNO, significa que se quiere ver el promedio de una semana, si es CERO, el de una quincena, y el segundo valor da que semana o que quincena.
  promedios = []
  if semana_quincena[0] == 1:
    for v in vendedores:
      s = (semana_quincena[1]-1) * 7
      prom = 0
      ac = 0
      for i in range(s,s+7):
        ac = ac + matriz[i][v]
        print (matriz[i][v])
      prom = ac/7
      promedios.append(prom)
  elif semana_quincena[0] == 0:
    for v in vendedores:
      s = (semana_quincena[1]-1) * 15
      prom = 0
      ac = 0
      for i in range(s,s+15):
        ac = ac + matriz[i][v]
      prom = ac/7
      promedios.append(prom)
  print ("====Promedios====")
  print (promedios)

      


ventas_totales(matriz_ventas)
promedio_vendedores(matriz_ventas,[0,2])
calcular_comisiones(matriz_ventas)
print(matriz_ventas)
calcular_promedios(matriz_ventas,[1,7,5,4],[0,2]) # Semana_quincena = [1,1], el primer valor si es UNO, significa que se quiere ver el promedio de una semana, si es CERO, el de una quincena, y el segundo valor da que semana o que quincena.


Vendedor 1  7000000
Vendedor 2  7320000
Vendedor 3  5940000
Vendedor 4  7880000
Vendedor 5  6660000
Vendedor 6  7180000
Vendedor 7  6530000
Vendedor 8  6820000
Vendedor 9  8280000
Vendedor 10  5670000
Promedio vendedor 0 : 233333.33333333334
Promedio vendedor 2 : 198000.0
COMISIONES-----------------------------------------------------------
[[     0  17000  14500  20000  22500 110000 120000  90000 160000  80000]
 [170000  20000  11000  23000  11000 130000  19500  20000  21500  22000]
 [ 10000  12500 130000 120000 120000  20500  19500 100000  10000  18500]
 [ 70000  15500  10500  23000  18000 110000  20500  19500 100000  12500]
 [ 19500 110000 120000  80000      0  12000      0  14500  10000  90000]
 [180000      0  70000  11500  30000  18000 120000  22500  80000  15500]
 [ 12500  22500  15000  21500  11500 100000  90000  21500 100000  18000]
 [ 13000 130000  10000  19500  11000  21500  23500 140000  13000  13000]
 [ 13500  30000 180000  14500  22500 110000  16000  19000  23000  80000]
